include ../config.mk

NAME=r_main

OBJS=version.o
OBJS+=rax2.o
OBJS+=rasm2.o
OBJS+=ragg2.o
OBJS+=rarun2.o
OBJS+=rabin2.o
OBJS+=rafind2.o
OBJS+=r2agent.o
OBJS+=radiff2.o
OBJS+=radare2.o
OBJS+=rahash2.o

#DEPS=r_util r_core r_syscall r_debug r_asm r_anal r_reg
WITH_LIBS=0
WITH_LIBR=1

include ../rules.mk
